name: eda
channels:
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - wandb==0.15.4
      - jupyterlab==4.0.4
      - seaborn==0.12.2
      - pandas==1.5.3
      - ydata-profiling==4.5.1
      - notebook==7.0.2
      #- pyarrow==2.0