name: basic_cleaning
channels:
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
      - mlflow==1.30.1
      - scikit-learn==1.3.0
      - matplotlib==3.7.2
      - pillow==8.1.2
      - pandas==1.5.3
